apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elk
resources:
  - namespace.yaml
  - elasticsearch.yaml
  - logstash.yaml
  - kibana.yaml
configMapGenerator:
  - name: logstash-config
    files:
      - logstash.yml=files/logstash.yml
  - name: logstash-pipeline
    files:
      - logstash.conf=files/logstash.conf
