input {
  beats {
    port => 5044
  }
}
output {
  if [instance] == "wp1" {
    pipeline { send_to => [wp1] }
  } else if [instance] == "wp2" {
    pipeline { send_to => [wp2] }
  } else {
    pipeline { send_to => [wp1] }
  }
}
