input {
  pipeline { address => wp1 }
}
filter {
  if [log][file][path] =~ /access\.log/ {
    grok {
      match => { "message" => "%{IPORHOST:client_ip} %{DATA:ident} %{DATA:auth} \[%{HTTPDATE:apache_ts}\] \"%{WORD:http_method} %{DATA:request} HTTP/%{NUMBER:http_version}\" %{NUMBER:status_code:int} (?:%{NUMBER:bytes:int}|-) \"%{DATA:referrer}\" \"%{DATA:ua}\"" }
    }
    date {
      match => [ "apache_ts", "dd/MMM/yyyy:HH:mm:ss Z" ]
      target => "@timestamp"
    }
  }
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "wordpress-logs"
    ilm_enabled => false
  }
}
