apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: elk-lab3
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
          resources:
            limits:
              memory: 3Gi
